---
# MANDATORY: Credentials for Salt master
SALT_URL: <salt_url>
SALT_USERNAME: <salt_usr>
SALT_PASSWORD: <salt_pwd>

# List of nodes (full fqdn) to skip in all tests
# TEMPORARY: please do not comment this setting.
skipped_nodes: [""]

# List of groups (short name, e.g. dbs) to skip in group tests
# TEMPORARY: please do not comment this setting.
skipped_groups: [""]

# mtu test setting
# this test may skip groups (see example)
test_mtu:
  { #"skipped_groups": ["dbs"]
    "skipped_ifaces": ["bonding_masters", "lo", "veth", "tap", "cali"]}
# mask for interfaces to skip

# ntp test setting
# this test may skip specific node (use fqdn)
test_ntp_sync:
  { #"skipped_nodes": [""],
    "time_deviation": 30}
